[buildPlans.iosevka-david35mm-extended]
family = "Iosevka david35mm Extended"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-david35mm-extended.variants]
  inherits = "ss02"

    [buildPlans.iosevka-david35mm-extended.variants.design]
    capital-c = "serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-i = "serifed"
    capital-j = "serifed"
    capital-q = "crossing"
    capital-s = "serifless"
    capital-t = "serifless"
    capital-x = "straight-serifless"
    capital-y = "straight-serifless"
    capital-z = "straight-serifless"
    a = "double-storey-serifless"
    c = "serifless"
    d = "toothed-serifless"
    f = "flat-hook-crossbar-at-x-height"
    j = "flat-hook-serifed"
    r = "serifed"
    t = "flat-hook"
    x = "straight-serifless"
    y = "straight-turn"
    z = "straight-serifless"
    long-s = "flat-hook"
    eszet = "sulzbacher"
    lower-lambda = "straight-turn"
    lower-xi = "flat-top"
    cyrl-capital-ze = "serifless"
    cyrl-che = "standard"
    cyrl-yery = "corner"
    zero = "slashed-oval"
    one = "base"
    four = "semi-open"
    five = "vertical-upper-left-bar"
    six = "straight-bar"
    seven = "straight-serifless"
    eight = "two-circles"
    nine = "straight-bar"
    asterisk = "hex-low"
    underscore = "high"
    caret = "medium"
    paren = "normal"
    brace = "straight"
    number-sign = "slanted"
    ampersand = "closed"
    at = "fourfold"
    dollar = "through-cap"
    cent = "open"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    lig-ltgteq = "slanted"
    ascii-single-quote = "straight"
    ascii-grave = "straight"
    punctuation-dot = "round"

  [buildPlans.iosevka-david35mm-extended.ligations]
  inherits = "dlig"

[buildPlans.iosevka-david35mm-extended.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-david35mm-extended.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-david35mm-extended.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
