align_args: true
align_parameter: true
align_table_field: true
break_after_functioncall_lp: true
break_after_functiondef_lp: true
break_after_operator: false
break_after_table_lb: false
break_before_functioncall_rp: false
break_before_functiondef_rp: false
break_before_table_rb: true
chop_down_kv_table: true
chop_down_parameter: true
chop_down_table: true
column_limit: 80
column_table_limit: 80
continuation_indent_width: 4
double_quote_to_single_quote: false
extra_sep_at_table_end: true
indent_width: 4
keep_simple_control_block_one_line: true
keep_simple_function_one_line: true
line_breaks_after_function_body: 1
line_separator: input
single_quote_to_double_quote: true
spaces_around_equals_in_field: true
spaces_before_call: 1
spaces_inside_functioncall_parens: false
spaces_inside_functiondef_parens: false
spaces_inside_table_braces: false
tab_width: 4
table_sep: ","
use_tab: false
